#!/bin/bash
#
# build with emcc
#

emcc src/shmupwarz.c \
    -std=c11 \
    -I./include \
    -I./include/vex \
    -I./include/emscripten \
    -O3 \
    -s WASM=1 \
    -s USE_WEBGL2=1 \
    -s USE_GLFW=3 \
    -s USE_SDL=2 \
    -s USE_SDL_IMAGE=2 \
    -s USE_SDL_MIXER=2 \
    -s USE_SDL_TTF=2 \
    -s SDL2_IMAGE_FORMATS='["png"]' \
    -o docs/index.html &> emcc.log

